version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3

    ports:
      - "5432:5432"

  app:
    build: .
    restart: 'no'
    volumes:
      - .:/src
      - ./migrations:/src/migrations
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  minio:
    container_name: minio
    image: minio/minio
    command: minio server --console-address ":9001" /data
    volumes:
      - minio-data1:/data1
      - minio-data2:/data2
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "9000:9000"
      - "9001:9001"
volumes:
  minio-data1:
  minio-data2:
