[tool.flake8]
ignore=["E203","E133", "W503"]
exclude = [".git","__pycache__","docs/source/conf.py","old,build,dist", "venv"]
max-complexity = 10
max-line-length = 79

[tool.black]
line-length = 79
include = '\.py$'
exclude = '''
(
    /(
        \.git
      | \.mypy_cache
      | venv
    )/
)

'''

[tool.isort]
line_length = 79
profile="black"
